/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SupabaseVehicleReference = {
  _type: "supabaseVehicleReference";
  vehicleId?: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  topBar?: {
    showTopBar?: boolean;
    phoneNumber?: string;
    phoneDisplayText?: string;
    address?: string;
    addressLink?: string;
  };
  trustBadges?: Array<
    {
      _key: string;
    } & TrustBadge
  >;
  mainNavigation?: Array<{
    label?: string;
    url?: string;
    children?: Array<{
      label?: string;
      url?: string;
      description?: string;
      _key: string;
    }>;
    _type: "navItem";
    _key: string;
  }>;
  headerCta?: {
    showCta?: boolean;
    buttonLabel?: string;
    buttonUrl?: string;
    buttonStyle?: "primary" | "secondary" | "outline";
  };
  footerLinkColumns?: Array<{
    title?: string;
    links?: Array<{
      label?: string;
      url?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  footerBottom?: {
    copyrightText?: string;
    legalLinks?: Array<{
      label?: string;
      url?: string;
      _key: string;
    }>;
  };
};

export type InventorySettings = {
  _id: string;
  _type: "inventorySettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  showFiltersSidebar?: boolean;
  itemsPerPage?: number;
  defaultSortOrder?:
    | "newest"
    | "price_asc"
    | "price_desc"
    | "mileage_asc"
    | "year_desc";
  showComparisonTool?: boolean;
  showQuickView?: boolean;
  filterOptions?: {
    showMakeFilter?: boolean;
    showModelFilter?: boolean;
    showYearFilter?: boolean;
    showPriceFilter?: boolean;
    showMileageFilter?: boolean;
    showBodyTypeFilter?: boolean;
    showFuelTypeFilter?: boolean;
    showTransmissionFilter?: boolean;
    showDrivetrainFilter?: boolean;
    showColorFilter?: boolean;
  };
  priceDisplay?: {
    showBiWeeklyPayment?: boolean;
    showMonthlyPayment?: boolean;
    defaultPaymentTerm?: number;
    defaultInterestRate?: number;
  };
  taxRate?: number;
  defaultDownPayment?: number;
  averageTradeInValue?: number;
  defaultTerm?: 36 | 48 | 60 | 72 | 84;
  creditTiers?: Array<{
    label?: string;
    minScore?: number;
    apr?: number;
    _key: string;
  }>;
  noResultsMessage?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SeoSettings = {
  _id: string;
  _type: "seoSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pagePath?: string;
  title?: string;
  description?: string;
  keywords?: Array<string>;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  canonicalUrl?: string;
  noIndex?: boolean;
  structuredData?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  showFiltersSidebar?: boolean;
  dealerName?: string;
  tagline?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  omvicLicense?: string;
  phone?: string;
  tollFree?: string;
  email?: string;
  address?: {
    street?: string;
    city?: string;
    province?: string;
    postalCode?: string;
    country?: string;
  };
  googleMapsUrl?: string;
  latitude?: number;
  longitude?: number;
  businessHours?: Array<{
    day?: string;
    open?: string;
    close?: string;
    isClosed?: boolean;
    _key: string;
  }>;
  hours?: {
    weekdays?: string;
    saturday?: string;
    sunday?: string;
  };
  financing?: {
    minDownPayment?: number;
    maxTerm?: number;
    defaultRate?: number;
  };
  financingDefaults?: {
    annualInterestRate?: number;
    amortizationMonths?: number;
  };
  delivery?: {
    freeDeliveryRadius?: number;
    perKmRate?: number;
    enabled?: boolean;
  };
  deliveryConfiguration?: {
    originPostalCode?: string;
    originLabel?: string;
    maxDeliveryDistanceKm?: number;
    freeDeliveryRadiusKm?: number;
  };
  leadRouting?: {
    salesEmail?: string;
    financeEmail?: string;
    tradeInEmail?: string;
  };
  leadRoutingRules?: Array<{
    role?: string;
    email?: string;
    _key: string;
  }>;
  depositAmount?: number;
  aggregateRating?: {
    ratingValue?: number;
    reviewCount?: number;
  };
  announcementBar?: {
    showBar?: boolean;
    message?: string;
    linkUrl?: string;
  };
  defaultSeo?: {
    metaTitle?: string;
    metaDescription?: string;
  };
  socialLinks?: {
    facebook?: string;
    facebookUrl?: string;
    instagram?: string;
    instagramUrl?: string;
    twitter?: string;
    twitterUrl?: string;
    youtube?: string;
    youtubeUrl?: string;
    tiktok?: string;
    linkedin?: string;
    googleMapsUrl?: string;
  };
  footerText?: string;
  copyrightText?: string;
};

export type ProtectionPlan = {
  _id: string;
  _type: "protectionPlan";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  slug?: Slug;
  active?: boolean;
  order?: number;
  ctaLabel?: string;
  ctaUrl?: string;
  highlights?: Array<{
    icon?: string;
    label?: string;
    _key: string;
  }>;
  name?: string;
  description?: string;
  price?: number;
  priceNote?: string;
  features?: Array<string>;
  coverage?: string;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type FaqEntry = {
  _id: string;
  _type: "faqEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  category?: "general" | "financing" | "trade-in" | "delivery" | "warranty";
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  location?: string;
  rating?: number;
  text?: string;
  body?: string;
  vehiclePurchased?: string;
  date?: string;
  featured?: boolean;
  order?: number;
  source?: "google" | "facebook" | "direct" | "dealerrater";
  customerPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  categories?: Array<string>;
  seoTitle?: string;
  seoDescription?: string;
};

export type Promotion = {
  _id: string;
  _type: "promotion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  active?: boolean;
  message?: string;
  ctaLabel?: string;
  ctaUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  startDate?: string;
  endDate?: string;
  discountType?: "percentage" | "amount" | "financing" | "addon";
  discountValue?: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroHeadline?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  active?: boolean;
  position?: "top" | "homepage" | "inventory" | "footer";
  content?: string;
  ctaLabel?: string;
  ctaUrl?: string;
  backgroundColor?: string;
  textColor?: string;
  startDate?: string;
  endDate?: string;
};

export type HomepageHero = {
  _id: string;
  _type: "homepageHero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  active?: boolean;
  headline?: string;
  subheadline?: string;
  ctaLabel?: string;
  ctaUrl?: string;
  secondaryCtaLabel?: string;
  secondaryCtaUrl?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  backgroundVideo?: string;
  overlayOpacity?: number;
};

export type CustomerAuthSettings = {
  _id: string;
  _type: "customerAuthSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  signIn?: {
    headline?: string;
    subheadline?: string;
    buttonText?: string;
  };
  signUp?: {
    headline?: string;
    subheadline?: string;
    buttonText?: string;
  };
  financeFields?: Array<{
    name?: string;
    label?: string;
    type?: string;
    required?: boolean;
    placeholder?: string;
    options?: Array<string>;
    order?: number;
    _key: string;
  }>;
  accountBenefits?: Array<{
    icon?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
};

export type CalculatorSettings = {
  _id: string;
  _type: "calculatorSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  taxRate?: number;
  defaultDownPayment?: number;
  defaultTerm?: number;
  creditTiers?: Array<{
    label?: string;
    minScore?: number;
    apr?: number;
    _key: string;
  }>;
  termOptions?: Array<number>;
  showBiWeekly?: boolean;
  disclaimer?: string;
};

export type DeliverySettings = {
  _id: string;
  _type: "deliverySettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  origin?: {
    address?: string;
    city?: string;
    province?: string;
    postalCode?: string;
    lat?: number;
    lng?: number;
  };
  deliveryTiers?: Array<{
    minKm?: number;
    maxKm?: number;
    costType?: string;
    cost?: number;
    label?: string;
    _key: string;
  }>;
  freeDeliveryRadius?: number;
  deliveryTimeEstimates?: Array<{
    maxDistance?: number;
    estimate?: string;
    _key: string;
  }>;
  enclosedTransport?: boolean;
  fullyInsured?: boolean;
  weekendDelivery?: boolean;
};

export type VdpSettings = {
  _id: string;
  _type: "vdpSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  inspection?: {
    enabled?: boolean;
    title?: string;
    description?: string;
    categories?: Array<{
      name?: string;
      icon?: string;
      points?: number;
      items?: Array<string>;
      _key: string;
    }>;
  };
  avilooBattery?: {
    enabled?: boolean;
    title?: string;
    showForEVOnly?: boolean;
    healthThresholds?: {
      excellent?: number;
      good?: number;
      fair?: number;
    };
  };
  requestCall?: {
    enabled?: boolean;
    title?: string;
    buttonText?: string;
    responseTime?: string;
  };
  ctaButtons?: Array<{
    label?: string;
    url?: string;
    icon?: string;
    style?: string;
    order?: number;
    _key: string;
  }>;
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
  category?: string;
  order?: number;
};

export type AiSettings = {
  _id: string;
  _type: "aiSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  annaAssistant?: {
    enabled?: boolean;
    displayName?: string;
    welcomeMessage?: string;
    quickActions?: Array<{
      label?: string;
      prompt?: string;
      icon?: string;
      _key: string;
    }>;
  };
  priceNegotiator?: {
    enabled?: boolean;
    negotiationRules?: {
      lowPriceThreshold?: number;
      lowPriceMaxDiscount_0_31days?: number;
      lowPriceMaxDiscount_32_46days?: number;
      lowPriceMaxDiscount_47plus?: number;
      highPriceMaxDiscount_0_46days?: number;
      highPriceMaxDiscount_47plus?: number;
    };
  };
  instantAppraisal?: {
    enabled?: boolean;
    offerValidDays?: number;
    hstRate?: number;
  };
  fees?: {
    adminFee?: number;
    certification?: number;
    licensing?: number;
    omvic?: number;
  };
  financing?: {
    lowestRate?: number;
    numberOfLenders?: number;
    terms?: Array<number>;
  };
};

export type SellPage = {
  _id: string;
  _type: "sellPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  hero?: {
    headline?: string;
    subheadline?: string;
    form?: {
      placeholderVin?: string;
      placeholderPlate?: string;
      buttonText?: string;
    };
  };
  benefits?: {
    sectionTitle?: string;
    items?: Array<{
      icon?: string;
      title?: string;
      description?: string;
      _key: string;
    }>;
  };
  cta?: {
    headline?: string;
    bonusText?: string;
    buttonText?: string;
    buttonUrl?: string;
  };
};

export type SellYourCarPage = {
  _id: string;
  _type: "sellYourCarPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heroSection?: {
    headline?: string;
    subheadline?: string;
    highlightText?: string;
    formSettings?: {
      vinPlaceholder?: string;
      licensePlatePlaceholder?: string;
      submitButtonText?: string;
    };
  };
  formSettings?: {
    enabled?: boolean;
    title?: string;
    ctaLabel?: string;
  };
  benefits?: Array<{
    icon?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
  whySellToUs?: {
    sectionTitle?: string;
    benefitItems?: Array<{
      icon?: string;
      title?: string;
      description?: string;
      _key: string;
    }>;
  };
  comparisonTable?: {
    sectionTitle?: string;
    headline?: string;
    planetMotorsLabel?: string;
    othersLabel?: string;
    headers?: Array<string>;
    rows?: Array<{
      cells?: Array<string>;
      feature?: string;
      planetMotors?: string;
      others?: string;
      highlight?: boolean;
      _key: string;
    }>;
  };
  avilooBattery?: {
    enabled?: boolean;
    title?: string;
    description?: string;
  };
  processSteps?: Array<{
    step?: number;
    title?: string;
    description?: string;
    _key: string;
  }>;
  testimonials?: Array<{
    name?: string;
    quote?: string;
    rating?: number;
    _key: string;
  }>;
  howItWorks?: {
    sectionTitle?: string;
    steps?: Array<{
      stepNumber?: number;
      title?: string;
      description?: string;
      _key: string;
    }>;
  };
  ctaSection?: {
    headline?: string;
    subheadline?: string;
    ctaLabel?: string;
    ctaUrl?: string;
  };
  seoTitle?: string;
  seoDescription?: string;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
  };
};

export type FinancingPage = {
  _id: string;
  _type: "financingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heroSection?: {
    headline?: string;
    subheadline?: string;
    highlight?: string;
    highlightText?: string;
    featuredRateText?: string;
    rateSubtext?: string;
    primaryCta?: {
      label?: string;
      url?: string;
    };
  };
  highlight?: string;
  formSettings?: {
    enabled?: boolean;
    title?: string;
    ctaLabel?: string;
  };
  benefitsSection?: {
    sectionTitle?: string;
    items?: Array<{
      icon?: string;
      title?: string;
      description?: string;
      _key: string;
    }>;
  };
  benefits?: Array<{
    icon?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
  calculator?: {
    defaultVehiclePrice?: number;
    defaultDownPayment?: number;
    defaultTerm?: number;
    termOptions?: Array<number>;
  };
  processSteps?: Array<{
    step?: number;
    title?: string;
    description?: string;
    _key: string;
  }>;
  howItWorks?: {
    sectionTitle?: string;
    steps?: Array<{
      stepNumber?: number;
      title?: string;
      description?: string;
      _key: string;
    }>;
  };
  ctaSection?: {
    headline?: string;
    subheadline?: string;
    ctaLabel?: string;
    ctaUrl?: string;
  };
  seoTitle?: string;
  seoDescription?: string;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
  };
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heroHeadline?: string;
  heroSubheadline?: string;
  heroCta?: CtaButton;
  heroSecondaryCta?: CtaButton;
  heroSection?: {
    headline?: string;
    headlineHighlight?: string;
    subheadline?: string;
    primaryCta?: {
      label?: string;
      url?: string;
    };
    secondaryCta?: {
      label?: string;
      url?: string;
    };
  };
  trustBadges?: Array<
    {
      _key: string;
    } & TrustBadge
  >;
  promoBanner?: {
    enabled?: boolean;
    showBanner?: boolean;
    text?: string;
    headline?: string;
    bodyText?: string;
    ctaLabel?: string;
    ctaUrl?: string;
    backgroundColor?: string;
  };
  quickFilters?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  financingPromo?: {
    rate?: string;
    rateLabel?: string;
    ctaLabel?: string;
    ctaUrl?: string;
  };
  announcementBar?: {
    show?: boolean;
    message?: string;
    linkText?: string;
    linkUrl?: string;
  };
  seoTitle?: string;
  seoDescription?: string;
  featuredVehicles?: Array<
    {
      _key: string;
    } & SupabaseVehicleReference
  >;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
  };
};

export type CtaButton = {
  _type: "ctaButton";
  label?: string;
  url?: string;
  text?: string;
  style?: string;
};

export type TrustBadge = {
  _type: "trustBadge";
  icon?: string;
  text?: string;
  title?: string;
  label?: string;
  description?: string;
  value?: string;
};

export type LenderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lender";
};

export type Vehicle = {
  _id: string;
  _type: "vehicle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: number;
  make?: string;
  model?: string;
  trim?: string;
  vin?: string;
  stockNumber?: string;
  price?: number;
  msrp?: number;
  specialPrice?: number;
  specialFinance?: LenderReference;
  status?: "available" | "in-transit" | "reserved" | "pending" | "sold";
  estimatedArrivalDate?: string;
  condition?: "new" | "used" | "certified";
  featured?: boolean;
  mileage?: number;
  exteriorColor?: string;
  interiorColor?: string;
  bodyStyle?:
    | "sedan"
    | "suv"
    | "truck"
    | "coupe"
    | "hatchback"
    | "wagon"
    | "van"
    | "convertible";
  fuelType?: "gasoline" | "diesel" | "electric" | "hybrid" | "phev";
  transmission?: "automatic" | "manual" | "cvt";
  drivetrain?: "fwd" | "rwd" | "awd" | "4wd";
  engine?: string;
  horsepower?: number;
  doors?: number;
  seats?: number;
  evRange?: number;
  batteryCapacity?: number;
  features?: Array<string>;
  safetyFeatures?: Array<string>;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  highlights?: Array<string>;
  carfaxUrl?: string;
  previousOwners?: number;
  accidentFree?: boolean;
  serviceHistory?: boolean;
  slug?: Slug;
  seoTitle?: string;
  seoDescription?: string;
};

export type Lender = {
  _id: string;
  _type: "lender";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  interestRate?: number;
  maxTerm?: number;
  featured?: boolean;
  order?: number;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<
    {
      _key: string;
    } & SanityAssistInstructionTask
  >;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<
    {
      _key: string;
    } & SanityAssistSchemaTypeField
  >;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type AssistInstructionContextReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "assist.instruction.context";
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference?: AssistInstructionContextReference;
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message?: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }
    | ({
        _key: string;
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string;
      } & SanityAssistInstructionContext)
    | ({
        _key: string;
      } & SanityAssistInstructionUserInput)
  >;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<
    | ({
        _key: string;
      } & SanityAssistOutputField)
    | ({
        _key: string;
      } & SanityAssistOutputType)
  >;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<
    {
      _key: string;
    } & SanityAssistInstruction
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SupabaseVehicleReference
  | Navigation
  | InventorySettings
  | SanityImageAssetReference
  | SeoSettings
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | ProtectionPlan
  | Slug
  | FaqEntry
  | Testimonial
  | BlogPost
  | Promotion
  | Page
  | Banner
  | HomepageHero
  | CustomerAuthSettings
  | CalculatorSettings
  | DeliverySettings
  | VdpSettings
  | FaqItem
  | AiSettings
  | SellPage
  | SellYourCarPage
  | FinancingPage
  | Homepage
  | CtaButton
  | TrustBadge
  | LenderReference
  | Vehicle
  | Lender
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
