/**
 * Banned-phrase guard.
 *
 * docs/HERO_HEADLINE.md formalises a list of headline / meta phrases that
 * are not permitted anywhere user-facing. They are saturated industry
 * cliches, retired headline candidates, or phrases that explicitly
 * conflict with the locked brand voice ("Battery-Health Certified Used
 * EVs"). This test guards every channel where copy is generated at
 * build time so a future bot edit cannot silently revert the work done
 * in PR #522 + chore/banned-phrase-sweep.
 *
 * The check covers:
 *
 *   1. Root site metadata (app/layout.tsx) — title, description, OG,
 *      Twitter card. Asserted via the regular metadata import.
 *   2. The shared SEO metadata helper (lib/seo/metadata.ts) — every
 *      page that calls generateSEOMetadata("Home", ...) inherits the
 *      Home title; we exercise that branch.
 *   3. The dynamic make/model meta description
 *      (app/cars/[make]/[model]/page.tsx) — verified against a sample
 *      slug. Sonar's history shows this is where the regression keeps
 *      coming back.
 *   4. The dynamic city CTA heading (app/used-cars/[city]/page.tsx) —
 *      verified by importing the city pool and asserting the literal
 *      heading string lives in source. (We can't render the page in
 *      isolation here without spinning up Next.js, so we sanity-check
 *      the source.)
 *   5. The blog post H2 we rewrote — same source-level check.
 */

import fs from "node:fs/promises"
import path from "node:path"
import { describe, expect, it } from "vitest"

const ROOT = path.join(__dirname, "..", "..")

/**
 * Phrases that must never appear in any production-facing copy. Keep in
 * lock-step with `docs/HERO_HEADLINE.md`. Match is case-insensitive.
 */
const BANNED_PHRASES = [
  "find your perfect",
  "find your dream",
  "drive the future",
  "the smarter way to buy",
  "buy with confidence",
  "experience vehicles like",
  "reimagined",
  "next-gen",
  "next-generation",
  "revolutionary",
] as const

function expectFreeOfBannedPhrases(label: string, text: string) {
  const haystack = text.toLowerCase()
  for (const phrase of BANNED_PHRASES) {
    expect(
      haystack.includes(phrase),
      `"${label}" must not contain banned phrase "${phrase}". ` +
        "See docs/HERO_HEADLINE.md for the canonical list."
    ).toBe(false)
  }
}

describe("banned-phrase guard", () => {
  it("root metadata in app/layout.tsx is clean", async () => {
    const file = await fs.readFile(path.join(ROOT, "app/layout.tsx"), "utf8")
    expectFreeOfBannedPhrases("app/layout.tsx", file)
  })

  it("shared SEO helper in lib/seo/metadata.ts is clean", async () => {
    const file = await fs.readFile(
      path.join(ROOT, "lib/seo/metadata.ts"),
      "utf8"
    )
    expectFreeOfBannedPhrases("lib/seo/metadata.ts", file)
  })

  it("dynamic make/model OG description is clean for a sample slug", async () => {
    // The metadata is generated by an async function, but the offending
    // string is a plain template literal in the source file. Reading
    // the file directly catches every regression without needing to
    // boot Next.js inside vitest.
    const file = await fs.readFile(
      path.join(ROOT, "app/cars/[make]/[model]/page.tsx"),
      "utf8"
    )
    expectFreeOfBannedPhrases("app/cars/[make]/[model]/page.tsx", file)
  })

  it("city landing page CTA heading is clean", async () => {
    const file = await fs.readFile(
      path.join(ROOT, "app/used-cars/[city]/page.tsx"),
      "utf8"
    )
    expectFreeOfBannedPhrases("app/used-cars/[city]/page.tsx", file)
  })

  it("trade-sell blog post body is clean", async () => {
    const file = await fs.readFile(
      path.join(ROOT, "lib/blog-posts/trade-sell.ts"),
      "utf8"
    )
    expectFreeOfBannedPhrases("lib/blog-posts/trade-sell.ts", file)
  })

  it("homepage hero canonical fallback is clean", async () => {
    const file = await fs.readFile(
      path.join(ROOT, "components/homepage-content.tsx"),
      "utf8"
    )
    expectFreeOfBannedPhrases("components/homepage-content.tsx", file)
  })

  it("BANNED_PHRASES list is non-empty and unique", () => {
    expect(BANNED_PHRASES.length).toBeGreaterThan(0)
    expect(new Set(BANNED_PHRASES).size).toBe(BANNED_PHRASES.length)
  })
})
