/**
 * lib/vdp/fallback-vehicle-data.ts
 *
 * Static fallback/demo vehicle data used by the VDP client when no real
 * vehicle is loaded from the server. This is the mock Tesla Model 3 used
 * for development, Storybook, and as a structural reference.
 *
 * Extracted from app/vehicles/[id]/vdp-client.tsx to keep that file
 * focused on rendering logic rather than data constants.
 */

import { calculateAllInPrice } from "@/lib/pricing/format"

export const FALLBACK_VEHICLE_DATA = {
  id: "2024-tesla-model-3",
  year: 2024,
  make: "Tesla",
  model: "Model 3",
  trim: "Long Range AWD",
  price: 52990,
  originalPrice: 56990,
  mileage: 12500,
  exteriorColor: "Pearl White Multi-Coat",
  interiorColor: "Black Premium",
  fuelType: "Electric",
  transmission: "Automatic",
  drivetrain: "AWD",
  engine: "Dual Motor",
  seats: 5,
  keys: 2,
  vin: "5YJ3E1EA1PF123456",
  stockNumber: "PM24-1234",
  carfaxUrl: "https://www.carfax.ca/vehicle/5YJ3E1EA1PF123456",
  carfaxScore: "No Accidents Reported",
  range: "576 km",
  batteryHealth: 98,
  batteryCapacity: "82 kWh",
  chargingSpeed: "250 kW DC",
  driveeMid: null as string | null,
  images: [] as string[],
  interiorImages: [] as string[],
  features: {
    comfortConvenience: ["Heated Seats", "Power Liftgate", "Wireless Charging", "Premium Audio"],
    safetySecurity: ["Autopilot", "Collision Avoidance", "Blind Spot Monitoring", "360 Camera"],
    entertainmentTech: ['15" Touchscreen', "Premium Connectivity", "Bluetooth", "USB-C Ports"],
    brakingTraction: ["Regenerative Braking", "Traction Control", "ABS", "Stability Control"],
  },
  specs: {
    range: "576 km",
    exterior: "Pearl White",
    interior: "Black",
    drive: "AWD",
  },
  packages: ["Premium Package", "Enhanced Autopilot"],
  inspectionScore: 210,
  inspectionCategories: [
    { name: "VIN & History", points: 10, icon: "history" },
    { name: "Powertrain & Engine", points: 22, icon: "engine" },
    { name: "Brakes & Suspension", points: 13, icon: "brakes" },
    { name: "Tyres & Wheels", points: 8, icon: "wheel" },
    { name: "Exterior", points: 21, icon: "car" },
    { name: "Interior", points: 20, icon: "interior" },
    { name: "Drive Test", points: 10, icon: "drive" },
    { name: "EV Systems", points: 12, icon: "ev" },
    { name: "Detailing & Safety", points: 94, icon: "safety" },
  ],
  inspectionItems: [
    { category: "Under the hood", status: "Passed" },
    { category: "Exterior", status: "Passed" },
    { category: "Interior", status: "Passed" },
    { category: "How it drives", status: "Passed" },
    { category: "How it looks", status: "Passed" },
    { category: "Detailing", status: "Passed" },
    { category: "History", status: "No reported accidents" },
  ],
  vinHistoryItems: [
    { item: "VIN verified (door jamb, dash, frame)", status: "Pass" },
    { item: "Lien search — no outstanding liens", status: "Pass" },
    { item: "CARFAX Canada history report clear", status: "Pass" },
    { item: "All outstanding recalls cleared", status: "Pass" },
    { item: "RCMP/CPIC stolen vehicle check — clear", status: "Pass" },
    { item: "Odometer accuracy verified", status: "Pass" },
    { item: "Clean Ontario title — no branding", status: "Pass" },
    { item: "No flood or water damage history", status: "Pass" },
    { item: "Airbag deployment history — none", status: "Pass" },
    { item: "Structural integrity — no frame damage", status: "Pass" },
  ],
  fullInspection: {
    vinHistory: [
      "VIN verified (door jamb, dash, frame)",
      "Lien search — no outstanding liens",
      "CARFAX Canada history report clear",
      "All outstanding recalls cleared",
      "RCMP/CPIC stolen vehicle check — clear",
      "Odometer accuracy verified",
      "Clean Ontario title — no branding",
      "No flood or water damage history",
      "Airbag deployment history — none",
      "Structural integrity — no frame damage",
    ],
    powertrainEngine: [
      "Engine oil level & condition",
      "Transmission fluid level & condition",
      "12V battery load test ≥ 75% capacity",
      "Alternator output & charging system",
      "Water pump — no leaks or noise",
      "Ignition system & spark plugs",
      "Fuel system — no leaks, proper pressure",
      "Radiator & coolant system",
      "Coolant level & freeze protection",
      "A/C system — cold air output verified",
      "No oil, coolant, or fluid leaks",
      "Belts & hoses — no cracks or wear",
      "Engine mounts — secure, no excess vibration",
      "Exhaust manifold — no leaks",
      "Catalytic converter function",
      "Timing belt/chain condition",
      "Valve cover gaskets — no leaks",
      "PCV valve function",
      "Air filter condition",
      "Throttle body & idle quality",
      "Turbo/supercharger (if equipped)",
      "Engine computer — no stored codes",
    ],
    brakesSuspension: [
      "Master cylinder & brake fluid level",
      "Front brake pad thickness ≥ 4mm",
      "Rear brake pad thickness ≥ 4mm",
      "Rotors & drums — no scoring or warping",
      "Brake calipers — no leaks, proper movement",
      "Brake lines & hoses — no damage",
      "Parking brake function verified",
      "Springs & shock absorbers — no leaks",
      "Control arm bushings & ball joints",
      "CV joints & axle boots",
      "Steering rack & tie rods",
      "Power steering fluid & pump operation",
      "Wheel bearings — no noise or play",
    ],
    tyresWheels: [
      'Tread depth all four tyres ≥ 4/32"',
      "No uneven wear, bulges or cracks",
      "Tyre pressure set to spec",
      "Alloy rims — no cracks or bends",
      "Valve stems & caps intact",
      "Lug nuts torqued to spec",
      "TPMS sensors functional",
      "Spare tyre & jack kit present",
    ],
    exterior: [
      "Exhaust system & Ontario emissions",
      "All exterior lights — headlights, tail, signal, fog",
      "Door locks, handles & hinges",
      "Windshield & glass — no chips, cracks",
      "Body panels — no damage, rust or corrosion",
      "Wipers, mirrors, bumpers & trim",
      "Hood, trunk & fuel door operation",
      "Paint condition assessment",
      "Undercarriage inspection",
      "Frame & structural integrity",
      "Door seals & weatherstripping",
      "Antenna & exterior accessories",
      "Licence plate lights",
      "Tow hooks & recovery points",
      "Roof rails (if equipped)",
      "Sunroof/moonroof operation",
      "Convertible top (if equipped)",
      "Running boards/side steps",
      "Mud flaps & wheel well liners",
      "Trailer hitch (if equipped)",
      "Parking sensors verified",
    ],
    interior: [
      "Instrument cluster & all warning lights",
      "Infotainment, navigation & Bluetooth",
      "All seats — power, heat, fold function",
      "Seatbelts, airbag system & SRS light",
      "HVAC, defroster & cabin air filter",
      "USB ports, horn, key fob & owner's manual",
      "Power windows all positions",
      "Power door locks",
      "Interior lighting — dome, map, ambient",
      "Sunvisors & vanity mirrors",
      "Center console & storage compartments",
      "Cup holders & armrests",
      "Carpet & floor mat condition",
      "Headliner condition",
      "Rear seat access & function",
      "Child seat anchors (LATCH)",
      "Trunk/cargo area condition",
      "12V/USB charging ports",
      "Garage door opener (if equipped)",
      "Voice control system",
    ],
    driveTest: [
      "Cold start & idle quality",
      "Transmission — smooth shifts all gears",
      "Braking performance — straight stop",
      "Acceleration & throttle response",
      "No abnormal suspension noise",
      "Drivetrain — no vibration or clunking",
      "10 km road test completed",
      "ADAS features — lane assist, AEB verified",
      "Regen braking function (EV/hybrid)",
      "No warning lights at end of road test",
    ],
    evSystems: [
      "High-voltage battery SOH & SOC",
      "Battery management system (BMS) — no faults",
      "Charge port — no damage, latches correctly",
      "L1 & L2 charging verified",
      "DC fast charging (if equipped)",
      "HV cables & connectors — no damage",
      "Electric motor — no noise or fault codes",
      "Battery thermal management system",
      "On-board charger (OBC) function",
      "Autopilot / FSD hardware (Tesla)",
      "Software version — latest OTA update",
      "Energy consumption within range spec",
    ],
    detailingSafety: [
      "Paint depth measurement — OEM thickness confirmed",
      "Dent & paintwork inspection — PDR where required",
      "Clay bar, paint correction & ceramic coat prep",
      "Full interior detail — vacuum, shampoo, odour elimination",
      "Ontario SSC safety standards certificate issued",
      "OMVIC disclosure package prepared & signed",
      "All keys, remotes & charge cables present",
      "OBD-II full diagnostic — zero fault codes",
      "Advanced safety systems — camera, radar, park sensors",
      "Final QC sign-off by certified Planet Motors technician",
    ],
  },
  conditionItems: [
    "Vehicle passes Ontario Safety Standards Certificate requirements",
    "All mechanical systems inspected by a licensed technician",
    "Battery state of health verified (for EVs)",
    "Professionally detailed — interior and exterior",
  ],
  ratings: {
    overall: 4.8,
    description:
      "The 2024 Tesla Model 3 combines advanced Tesla technology with unmatched performance and acceleration. Perfect for Canadian drivers looking for a premium EV experience.",
    categories: [
      { name: "Performance", score: 4.9 },
      { name: "Efficiency", score: 5 },
      { name: "Comfort", score: 4.5 },
      { name: "Tech", score: 5 },
      { name: "Space", score: 4.2 },
      { name: "Reliability", score: 4.7 },
      { name: "Safety", score: 4.9 },
    ],
  },
  protectionPackages: [
    {
      name: "Basic",
      paymentMethod: "Cash only",
      moneyBack: true,
      dueAtCheckout: "Full purchase price",
      warranty: "—",
      tireRim: "—" as string | boolean,
      gapCoverage: "—",
      lifeDisability: "—",
      price: "Included",
      recommended: false,
    },
    {
      name: "Essential Shield",
      paymentMethod: "Cash or Finance",
      moneyBack: true,
      dueAtCheckout: "$250 refundable deposit",
      warranty: "Standard",
      tireRim: "—" as string | boolean,
      gapCoverage: "$50K",
      lifeDisability: "—",
      price: "$1,950",
      recommended: false,
    },
    {
      name: "Planet Care™",
      paymentMethod: "Cash or Finance",
      moneyBack: true,
      dueAtCheckout: "$250 refundable deposit",
      warranty: "Extended to 2034",
      tireRim: "—" as string | boolean,
      gapCoverage: "$60K",
      lifeDisability: "~$1M life",
      price: "$3,000",
      recommended: true,
    },
    {
      name: "Planet Care Plus™",
      paymentMethod: "Finance only",
      moneyBack: true,
      dueAtCheckout: "$250 refundable deposit",
      warranty: "Extended to 2034",
      tireRim: true as string | boolean,
      gapCoverage: "$60K",
      lifeDisability: "~$1M life",
      price: "$4,850",
      recommended: false,
    },
  ],
  pricing: (() => {
    const breakdown = calculateAllInPrice(52990)
    return {
      vehiclePrice: breakdown.vehiclePrice,
      deliveryFee: 0,
      hst: breakdown.hst,
      omvicFee: breakdown.omvicFee,
      certificationFee: breakdown.certificationFee,
      licensingReg: breakdown.licensingFee,
      totalWithHst: breakdown.total,
    }
  })(),
  history: {
    owners: 1,
    accidents: 0,
    serviceRecords: 8,
    lastServiced: "2024-02-15",
  },
} as const
