/**
 * Lightweight blog post metadata for listing pages.
 *
 * This module is intentionally standalone — it does NOT import from
 * lib/blog-data or the blog-posts chunk files so that client components
 * (e.g. blog-page-content.tsx) can import metadata without pulling the
 * large `content` strings (~86 KB) into the client bundle.
 *
 * When adding a new blog post, add its metadata entry here as well as
 * the full post entry in the appropriate lib/blog-posts/*.ts chunk file.
 */

export type BlogPostMeta = {
  slug: string
  title: string
  excerpt: string
  date: string
  readTime: string
  category: string
  image: string
  author: string
}

/** All static blog posts in reverse-chronological order. */
export const blogPostsMeta: BlogPostMeta[] = [
  // ── ev-tesla chunk ──────────────────────────────────────────────────────────
  { slug: "check-battery-health-used-tesla-canada", title: "How to Check Battery Health Before Buying a Used Tesla in Canada", excerpt: "Every pre-owned Tesla undergoes a rigorous 50-point battery health diagnostic. See how we measure degradation and capacity.", date: "Apr 09, 2026", readTime: "8 min read", category: "Electric Vehicles", image: "/images/blog/8.png", author: "Planet Motors Team" },
  { slug: "trading-in-car-with-loan-canada", title: "Trading In a Car With a Loan in Canada: What Happens Next?", excerpt: "Find out what happens when you trade in a vehicle that still has a loan or lien. We break down the process, payoff calculations, and what dealers handle.", date: "Apr 02, 2026", readTime: "7 min read", category: "Trade-In", image: "/images/blog/IMG_3792-scaled.jpg", author: "Planet Motors Team" },
  { slug: "buying-used-tesla-canada-2026-guide", title: "Buying a Used Tesla in Canada: Is It Worth It? (2026 Guide)", excerpt: "Thinking of buying a pre-owned Tesla in Canada? Learn what to look for, from battery health to cold-weather performance, in our complete buyer's guide.", date: "Mar 26, 2026", readTime: "12 min read", category: "Electric Vehicles", image: "/images/blog/IMG_4474-scaled.jpg", author: "Planet Motors Team" },
  { slug: "increase-car-value-before-selling-ontario", title: "How to Increase Your Car's Value Before Selling in Ontario", excerpt: "Simple tips to boost your vehicle's resale value — from detailing and minor repairs to documentation and timing your sale right.", date: "Mar 18, 2026", readTime: "7 min read", category: "Selling", image: "/images/blog/Untitled-design-20.png", author: "Planet Motors Team" },
  { slug: "tesla-warranty-used-cars", title: "Tesla Warranty for Used Cars: What You Need to Know", excerpt: "Understand what Tesla's warranty covers on pre-owned vehicles, how to check remaining coverage, and what's included when buying from a third-party dealer.", date: "Mar 10, 2026", readTime: "6 min read", category: "Electric Vehicles", image: "/images/blog/IMG_1903-2-scaled.jpg", author: "Planet Motors Team" },
  { slug: "trade-in-vs-selling-car-ontario", title: "Trade-In vs Selling Your Car to a Dealer in Ontario", excerpt: "Discover the pros and cons of trading in versus selling your car privately. Learn which option gives you the best value and convenience when upgrading your vehicle.", date: "Feb 20, 2026", readTime: "8 min read", category: "Selling", image: "/images/blog/Mode-2-2.png", author: "Planet Motors Team" },
  { slug: "tesla-full-self-driving-guide", title: "What Is Tesla Full Self-Driving (FSD)? Complete Buyer Guide", excerpt: "Everything you need to know about Tesla's Full Self-Driving capability, including features, pricing, and what to expect when purchasing a Tesla with FSD.", date: "Feb 10, 2026", readTime: "10 min read", category: "Electric Vehicles", image: "/images/blog/Mode-2-1.png", author: "Planet Motors Team" },
  { slug: "biweekly-vs-monthly-payments-canada", title: "Bi-Weekly vs Monthly Car Payments in Canada: Which is Better?", excerpt: "Compare bi-weekly and monthly payment schedules to determine which option saves you more money and fits your budget best.", date: "Feb 02, 2026", readTime: "6 min read", category: "Financing", image: "/images/blog/Mode-2.png", author: "Planet Motors Team" },
  // ── trade-sell chunk ─────────────────────────────────────────────────────────
  { slug: "tesla-model-y-vs-model-3", title: "A Detailed Side-by-Side Comparison of Tesla's Top Models", excerpt: "Compare the Tesla Model 3 vs. Model Y side by side — range, cargo space, performance, and pricing to help you pick the right EV.", date: "Jan 26, 2026", readTime: "12 min read", category: "Electric Vehicles", image: "/images/blog/Mode.png", author: "Planet Motors Team" },
  { slug: "awd-vs-rwd-ontario", title: "AWD vs RWD: Which Is Better to Drive in Ontario?", excerpt: "Understand the differences between all-wheel drive and rear-wheel drive, and which drivetrain is best for Ontario's varying weather conditions.", date: "Jan 09, 2026", readTime: "7 min read", category: "Buying Guide", image: "/images/blog/Banner-2-1.png", author: "Planet Motors Team" },
  { slug: "we-buy-your-car-canada", title: "We Buy Your Car Across Canada", excerpt: "At Planet Motors, we buy your car anywhere in Canada, fast and hassle-free with no hidden fees. Get instant cash and turn your car into cash today!", date: "Oct 24, 2025", readTime: "5 min read", category: "Selling", image: "/images/blog/image-1-1024x579-1.jpg", author: "Planet Motors Team" },
  { slug: "sell-car-for-cash-canada", title: "Quick Guide: Sell Your Car for Cash In Canada", excerpt: "Sell your car for cash in Canada with confidence. Planet Motors offers fair prices, fast deals, and hassle-free paperwork.", date: "Sep 30, 2025", readTime: "6 min read", category: "Selling", image: "/images/blog/image-4-1024x579-1.png", author: "Planet Motors Team" },
  { slug: "why-choose-planet-motors", title: "Why Choose Planet Motors?", excerpt: "Planet Motors offers used luxury cars and Teslas in Richmond Hill. Enjoy trusted service, transparent pricing, and flexible financing tailored to you.", date: "Sep 24, 2025", readTime: "5 min read", category: "Company", image: "/images/blog/image-2-1024x572-1.png", author: "Planet Motors Team" },
  { slug: "how-to-trade-in-used-car", title: "How to Trade in Your Used Car", excerpt: "Nearly 50% of Canadians choose to trade in their used cars when buying their next vehicle. It's a quick and hassle-free way to upgrade.", date: "Sep 03, 2025", readTime: "8 min read", category: "Trade-In", image: "/images/blog/image-1-1024x572-1.png", author: "Planet Motors Team" },
  { slug: "car-resale-value-toronto", title: "Car Resale Value: How to Maximize it in Toronto", excerpt: "Discover proven tips to maximize your car's resale value. From regular maintenance and detailing to timing your sale.", date: "Aug 19, 2025", readTime: "9 min read", category: "Selling", image: "/images/blog/unnamed-2.jpg", author: "Planet Motors Team" },
  { slug: "tax-benefits-trade-in-vs-selling", title: "Tax Benefits of Trading In Your Car vs Selling Privately", excerpt: "Planet Motors explains the tax benefits of trading in your car vs selling it privately. Learn which option helps you save more.", date: "Aug 06, 2025", readTime: "7 min read", category: "Financing", image: "/images/blog/unnamed-5.jpg", author: "Planet Motors Team" },
  // ── finance-tips chunk ───────────────────────────────────────────────────────
  { slug: "sell-financed-car-canada", title: "How to Sell a Financed Car in Canada?", excerpt: "Thinking of selling your financed car in Canada? Learn the step-by-step process, key legal requirements, and expert tips.", date: "Jul 17, 2025", readTime: "10 min read", category: "Selling", image: "/images/blog/unnamed-8.jpg", author: "Planet Motors Team" },
  { slug: "sell-car-toronto-guide", title: "How to Sell a Car in Toronto: The Ultimate Owner's Manual", excerpt: "Planning to sell your car in Toronto? Get the ultimate owner's manual on paperwork, pricing, and how to get the most value for your vehicle today.", date: "Jul 14, 2025", readTime: "12 min read", category: "Selling", image: "/images/blog/unnamed-9.jpg", author: "Planet Motors Team" },
  { slug: "sell-everything-before-sell", title: "Sell Your Car: Everything You Need to Know Before You Sell", excerpt: "Whether you're upgrading to a new vehicle or simply want to cash out, knowing the right steps can help you get the best deal.", date: "Aug 26, 2025", readTime: "8 min read", category: "Selling", image: "/images/blog/unnamed.jpg", author: "Planet Motors Team" },
  { slug: "get-quote-5-minutes", title: "Get a Quote in 5 Minutes from Planet Motors", excerpt: "Why wait? Get your personalized quote in just 5 minutes at Planet Motors. Fast, hassle-free, and no pressure.", date: "Jul 22, 2025", readTime: "4 min read", category: "Company", image: "/images/blog/unnamed-6.jpg", author: "Planet Motors Team" },
  { slug: "tesla-cybertruck-2024", title: "Tesla Cybertruck: A Revolutionary Electric Pickup in 2024!", excerpt: "The electric truck market is moving fast, and 2024 is a breakout year with the much-anticipated release of the Tesla Cybertruck.", date: "May 12, 2025", readTime: "10 min read", category: "Electric Vehicles", image: "/images/blog/blog-2.png", author: "Planet Motors Team" },
  { slug: "equifax-newcomers-credit-canada", title: "Equifax Lets Newcomers Import Credit Scores to Canada", excerpt: "Navigating Canada's financial system as a newcomer can be challenging, particularly without a Canadian credit score.", date: "May 12, 2025", readTime: "6 min read", category: "Financing", image: "/images/blog/blog-1.png", author: "Planet Motors Team" },
  { slug: "tesla-robotaxi-robovan", title: "The Future of Autonomous Vehicles: Tesla Unveils Robotaxi and Robovan", excerpt: "Tesla's recent reveal of its autonomous Robotaxi and Robovan has set a new benchmark in the race for self-driving vehicles.", date: "Oct 19, 2024", readTime: "8 min read", category: "Electric Vehicles", image: "/images/blog/blog-3.png", author: "Planet Motors Team" },
  { slug: "ev-trends-planet-motors", title: "New Trends in EV: Leading the Charge at Planet Motors Canada", excerpt: "The electric vehicle (EV) market is evolving rapidly, with exciting trends shaping the future of driving.", date: "Oct 17, 2024", readTime: "7 min read", category: "Electric Vehicles", image: "/images/blog/blog-4.png", author: "Planet Motors Team" },
  // ── market-news chunk ────────────────────────────────────────────────────────
  { slug: "car-deliveries-canada", title: "Car Deliveries in Canada: What You Need to Know", excerpt: "Buying a car has become more convenient than ever, especially when it comes to car deliveries across Canada.", date: "Oct 11, 2024", readTime: "5 min read", category: "Buying Guide", image: "/images/blog/blog-6.png", author: "Planet Motors Team" },
  { slug: "understanding-apr-car-loans", title: "Understanding APR in Car Loans: What You Need to Know", excerpt: "When considering financing for your next vehicle purchase at Planet Motors, understanding the Annual Percentage Rate (APR) is essential.", date: "Oct 02, 2024", readTime: "6 min read", category: "Financing", image: "/images/blog/blog6-1.png", author: "Planet Motors Team" },
  { slug: "top-cars-fall-winter-2024", title: "Top Cars for Fall & Winter Driving in 2024", excerpt: "Discover the best vehicles for tackling Ontario's challenging fall and winter driving conditions.", date: "Oct 01, 2024", readTime: "9 min read", category: "Buying Guide", image: "/images/blog/blog7-1.jpg", author: "Planet Motors Team" },
  { slug: "top-preowned-vehicles-2024", title: "Top Pre-Owned Vehicles to Consider in 2024", excerpt: "Choosing the right pre-owned vehicle can be a challenge, but it's well worth the effort. At Planet Motors, we've curated a selection of the best.", date: "Sep 13, 2024", readTime: "10 min read", category: "Buying Guide", image: "/images/blog/blog-8.png", author: "Planet Motors Team" },
  { slug: "tesla-model-y-future-ev", title: "Tesla Model Y: The Future of EVs at Your Fingertips", excerpt: "This electric crossover combines innovation, performance, and futuristic design, making it a top choice for those looking to experience the EV revolution.", date: "Sep 12, 2024", readTime: "8 min read", category: "Electric Vehicles", image: "/images/blog/blog9-1.jpg", author: "Planet Motors Team" },
  { slug: "first-time-car-buyer-financing", title: "A Beginner's Guide to First-Time Car Buyer Financing in Canada", excerpt: "Buying your first car is an exciting milestone, but navigating the car financing process can be overwhelming.", date: "Aug 29, 2024", readTime: "11 min read", category: "Financing", image: "/images/blog/blog-10.png", author: "Planet Motors Team" },
  { slug: "best-selling-electric-cars-canada-2023", title: "Learn about the best-selling electric cars in Canada (2023)", excerpt: "The high cost of gas has generated a lot of interest in electric cars (EV), with many more possibilities now than a year ago.", date: "Nov 08, 2023", readTime: "7 min read", category: "Electric Vehicles", image: "/images/blog/blog-11.png", author: "Planet Motors Team" },
  { slug: "honda-civic-hybrid-2024", title: "Honda Says It Will Bring Back the Civic Hybrid in 2024", excerpt: "Canada is seeing Honda create a Civic Hybrid for the first time since 2015. The fuel-efficient Civic will go into production in the spring.", date: "Oct 26, 2023", readTime: "5 min read", category: "Industry News", image: "/images/blog/blog12-1.jpg", author: "Planet Motors Team" },
]
