/**
 * 360° frame URL builder — Supabase Storage.
 *
 * All walk-around frames have been migrated from Drivee's Firebase Storage
 * to our own Supabase Storage bucket (`vehicle-360`).
 *
 * URL pattern (public, no auth required):
 *   {SUPABASE_URL}/storage/v1/object/public/vehicle-360/{MID}/nobg/{NN}.webp
 *
 * The "nobg" subfolder contains background-removed transparent WebP frames
 * (processed via rembg AI). Original frames are preserved at {MID}/{NN}.webp.
 * Both frameUrl() and scripts/migrate-360-to-supabase.ts use the nobg/ path.
 *
 * A static manifest records the exact frame count per MID so we no longer
 * need 50 parallel HEAD requests to discover frames at runtime — the API
 * route can respond instantly.
 */

const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ?? "https://ldervbcvkoawwknsemuz.supabase.co"
const BUCKET = "vehicle-360"

/**
 * Static manifest of MID → frame count.
 * Generated by `scripts/migrate-360-to-supabase.ts` on 2026-04-15.
 * Update this map whenever new vehicles are photographed and migrated.
 */
export const FRAME_MANIFEST: Record<string, number> = {
  "190171976531": 37, // 2021 Jeep Wrangler 4xe
  "744761075195": 33, // 2025 Chevrolet Equinox EV
  "132601940353": 40, // 2023 Tesla Model 3 Long Range
  "806787519944": 36, // 2023 Volkswagen Taos
  "890747363179": 40, // 2024 Tesla Model 3
  "640326639530": 39, // 2019 Tesla Model 3
  "061789806057": 7,  // 2022 Tesla Model 3
  "396425623701": 39, // 2018 Volkswagen Tiguan
  "625294835450": 38, // 2025 Hyundai Kona Electric
  "085109772520": 37, // 2018 Audi Q3
  "860125156862": 32, // 2021 Tesla Model 3 (2nd)
}

/**
 * Interior panorama manifest — MID → interior image filename.
 * These are equirectangular Insta360 photos uploaded to the same bucket.
 * Only vehicles with interior shots are listed here.
 */
export const INTERIOR_MANIFEST: Record<string, string> = {
  "190171976531": "interior.jpg", // 2021 Jeep Wrangler 4xe
}

/** Build the public Supabase Storage URL for an interior panorama, or null. */
export function interiorUrl(mid: string): string | null {
  const filename = INTERIOR_MANIFEST[mid]
  if (!filename) return null
  return `${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${mid}/${filename}`
}

/** Build the public Supabase Storage URL for a single walk-around frame (background-removed). */
export function frameUrl(mid: string, frameNumber: number): string {
  const padded = String(frameNumber).padStart(2, "0")
  return `${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${mid}/nobg/${padded}.webp`
}

/**
 * Return all frame URLs for a given MID.
 *
 * Uses the static manifest for instant lookup (no network requests).
 * Falls back to probing Supabase Storage if the MID isn't in the manifest
 * (e.g. newly added vehicles before the manifest is updated).
 */
export async function discoverFrameUrls(mid: string): Promise<string[]> {
  const count = FRAME_MANIFEST[mid]

  if (count != null && count > 0) {
    // Fast path — use the manifest (no network calls)
    return Array.from({ length: count }, (_, i) => frameUrl(mid, i + 1))
  }

  // Slow path — probe Supabase Storage for unknown MIDs
  const MAX_PROBE = 50
  const probes = Array.from({ length: MAX_PROBE }, (_, i) => {
    const url = frameUrl(mid, i + 1)
    return fetch(url, { method: "HEAD" })
      .then((res) => ({ url, ok: res.ok }))
      .catch(() => ({ url, ok: false }))
  })

  const results = await Promise.all(probes)
  const urls: string[] = []
  for (const result of results) {
    if (!result.ok) break
    urls.push(result.url)
  }
  return urls
}
