-- Planet Motors: Composite User-Query Indexes
-- Migration: 009_composite_user_query_indexes.sql
-- Run with: psql $DATABASE_URL -f scripts/009_composite_user_query_indexes.sql
--
-- These cover multi-column predicate + ORDER BY patterns generated by the
-- customer-facing API routes. The existing scalar indexes in 003/004/007 are
-- sufficient for admin lookups but cannot satisfy user-scoped ordered queries in
-- a single Index Scan. Each index below eliminates a Sort + separate Bitmap index
-- node that would otherwise appear in EXPLAIN ANALYZE.
--
-- All indexes use CONCURRENTLY to avoid table locks on the production replica.
-- CONCURRENTLY requires autocommit; do NOT wrap this file in a transaction block.

-- ─────────────────────────────────────────────────────────────────
-- finance_applications_v2
-- ─────────────────────────────────────────────────────────────────

-- "My applications" list, ordered newest-first
-- Covers: WHERE user_id = ? ORDER BY created_at DESC
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_finance_apps_v2_user_date
  ON finance_applications_v2 (user_id, created_at DESC);

-- "My active applications" filter used by the dashboard badge
-- Covers: WHERE user_id = ? AND status NOT IN ('cancelled', 'declined')
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_finance_apps_v2_user_status
  ON finance_applications_v2 (user_id, status);

-- ─────────────────────────────────────────────────────────────────
-- finance_documents
-- ─────────────────────────────────────────────────────────────────

-- Document list per application, ordered by upload date
-- Covers: WHERE application_id = ? ORDER BY uploaded_at DESC
-- (existing idx_documents_application is unordered)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_finance_documents_app_date
  ON finance_documents (application_id, uploaded_at DESC);

-- ─────────────────────────────────────────────────────────────────
-- orders
-- ─────────────────────────────────────────────────────────────────

-- "My order history" with active-status filter
-- Covers: WHERE customer_id = ? AND status = ? ORDER BY created_at DESC
-- (existing indexes are three separate unordered scalar indexes)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_customer_status_date
  ON public.orders (customer_id, status, created_at DESC);

-- ─────────────────────────────────────────────────────────────────
-- trade_in_quotes
-- ─────────────────────────────────────────────────────────────────

-- "My trade-in history" list, ordered newest-first
-- Covers: WHERE user_id = ? ORDER BY created_at DESC
-- (existing idx_trade_in_quotes_user_id is unordered)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_trade_in_quotes_user_date
  ON trade_in_quotes (user_id, created_at DESC);

-- ─────────────────────────────────────────────────────────────────
-- vehicles  (supplement to 008_inventory_performance_indexes.sql)
-- ─────────────────────────────────────────────────────────────────

-- Stock-number lookup used by VDP routes, admin search, and order joins.
-- UNIQUE constraint may already exist on some deployments; IF NOT EXISTS is safe.
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS idx_vehicles_stock_number
  ON vehicles (stock_number);
